### ISSUE TITLE
Statistic test

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [KrishnaswamyLab/phemd#4]
Hi,
first of all thanks for have developed this tool.
I'm interested to use PhEMD but somethings is unclear to me. Once we found the different groups on the diffusion map what kind of statistical test should I use to say ok the group1 is different from group2 due to ClusterX or ClusterY? We may download a table with frequencies of Clusters for each specimens and use them to perform Mann–Whitney U-test?

Thanks a lot.

Best,
Domenico

**Comment by wschen** [comment]
Hi Domenico,
You raise an interesting question about assessing significance in terms of differences between the final clusters of single-cell specimens. My impression is that the Mann-Whitney U-test is not the test you are looking for here as the cell subtypes types are not ordinal variable (i.e. cell subtype 3 is not "greater" than cell subtype 2 which is not "greater" than subtype 1).

More broadly speaking, assessing the "significance" of difference between two clusters may seem a bit counterintuitive because in some sense the clusters were defined to maximize differences between them. SigClust or the approach from Kimes et al. Biometrics 2017 may be of interest to assess the significance of the clustering in general, although I have to admit I have not looked into these approaches in much detail. Hope this is of some help!
